server:
  port: 9000

spring:
  application:
    name: invenotry-service
    
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory    username: postgres
    password: root
    
  jpa:    properties:      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
        format_sql: true
        
    hibernate:      ddl-auto: update
    show-sql: true
  